version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:12.1
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db_data: