version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "flask init_app && flask run --host 0.0.0.0"
    volumes:
      - ./web
    ports:
      - "5000:5000"

  postgres:
    image: postgres:12.1
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: